### ISSUE TITLE
AssertionError: The observation returned by the `reset()` method is not contained with the observation space (Discrete(581))

### ISSUE THREAD

**Issue by 0xdarkman** [NickKaparinos/Automated-Cryptocurrency-trading-using-Deep-RL#3]
I am seeing following ERROR when I run main_DQN.py.
I created hdf5 datasets downloading 1min data from binance and saving with pandas to hdf5 format.

```
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.58it/s]
/usr/local/anaconda3/envs/py38/lib/python3.8/site-packages/gym/utils/passive_env_checker.py:216: UserWarning: WARN: Future gym versions will require that `Env.reset` can be passed a `seed` instead of using `Env.seed` for resetting the environment random number generator.
  logger.warn(
/usr/local/anaconda3/envs/py38/lib/python3.8/site-packages/gym/utils/passive_env_checker.py:228: UserWarning: WARN: Future gym versions will require that `Env.reset` can be passed `return_info` to return information from the environment resetting.
  logger.warn(
/usr/local/anaconda3/envs/py38/lib/python3.8/site-packages/gym/utils/passive_env_checker.py:233: UserWarning: WARN: Future gym versions will require that `Env.reset` can be passed `options` to allow the environment initialisation to be passed additional information.
  logger.warn(
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/py38/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/anaconda3/envs/py38/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/anaconda3/envs/py38/lib/python3.8/site-packages/tianshou/env/worker/subproc.py", line 95, in _worker
    retval = env.reset(**data)
  File "/usr/local/anaconda3/envs/py38/lib/python3.8/site-packages/gym/wrappers/time_limit.py", line 66, in reset
    return self.env.reset(**kwargs)
  File "/usr/local/anaconda3/envs/py38/lib/python3.8/site-packages/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
  File "/usr/local/anaconda3/envs/py38/lib/python3.8/site-packages/gym/wrappers/env_checker.py", line 47, in reset
    return passive_env_reset_check(self.env, **kwargs)
  File "/usr/local/anaconda3/envs/py38/lib/python3.8/site-packages/gym/utils/passive_env_checker.py", line 247, in passive_env_reset_check
    _check_obs(obs, env.observation_space, "reset")
  File "/usr/local/anaconda3/envs/py38/lib/python3.8/site-packages/gym/utils/passive_env_checker.py", line 113, in _check_obs
    assert observation_space.contains(
AssertionError: The observation returned by the `reset()` method is not contained with the observation space (Discrete(581))
Traceback (most recent call last):
  File "main_DQN.py", line 128, in <module>
    main()
  File "main_DQN.py", line 93, in main
    train_collector = ts.data.Collector(policy, train_envs, PVRB(**replay_buffer_hyperparameters),
  File "/usr/local/anaconda3/envs/py38/lib/python3.8/site-packages/tianshou/data/collector.py", line 77, in __init__
    self.reset(False)
  File "/usr/local/anaconda3/envs/py38/lib/python3.8/site-packages/tianshou/data/collector.py", line 120, in reset
    self.reset_env(gym_reset_kwargs)
  File "/usr/local/anaconda3/envs/py38/lib/python3.8/site-packages/tianshou/data/collector.py", line 136, in reset_env
    rval = self.env.reset(**gym_reset_kwargs)
  File "/usr/local/anaconda3/envs/py38/lib/python3.8/site-packages/tianshou/env/venvs.py", line 203, in reset
    ret_list = [self.workers[i].recv() for i in id]
  File "/usr/local/anaconda3/envs/py38/lib/python3.8/site-packages/tianshou/env/venvs.py", line 203, in <listcomp>
    ret_list = [self.workers[i].recv() for i in id]
  File "/usr/local/anaconda3/envs/py38/lib/python3.8/site-packages/tianshou/env/worker/subproc.py", line 214, in recv
    result = self.parent_remote.recv()
  File "/usr/local/anaconda3/envs/py38/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/local/anaconda3/envs/py38/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/local/anaconda3/envs/py38/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```

**Comment by 0xdarkman** [comment]
`state_shape = env.observation_space.shape or env.observation_space.n`

env.observation_space = Discrete(581)
state_shape = 581

I see NN observation space is the reason of my error but how to fix it?

**Comment by NickKaparinos** [comment]
I cannot know what caused the error, but I suspect it has may have something to do with your data. Make sure your data has 4 columns and TradeEnv.data has num_cryptos * 7 columns.

**Comment by 0xdarkman** [comment]
I have resampled OHLC data to hourly as below (ADAUSDT):

```
                         open      high       low     close
open_time
2018-04-17 04:00:00  0.265447  0.266997  0.264304  0.265502
2018-04-17 05:00:00  0.269207  0.270196  0.268395  0.269129
2018-04-17 06:00:00  0.255592  0.256385  0.254357  0.255295
2018-04-17 07:00:00  0.259237  0.259770  0.258674  0.259179
2018-04-17 08:00:00  0.255278  0.255838  0.254777  0.255230
...                       ...       ...       ...       ...
2022-08-01 19:00:00  0.506185  0.506458  0.505883  0.506190
2022-08-01 20:00:00  0.507862  0.508158  0.507593  0.507943
2022-08-01 21:00:00  0.508765  0.508963  0.508513  0.508718
2022-08-01 22:00:00  0.508605  0.508938  0.508278  0.508640
2022-08-01 23:00:00  0.512170  0.512542  0.511897  0.512182

[37540 rows x 4 columns]
```


...but I still get the same error.

Do you maybe have an idea why?

You mentioned "TradeEnv.data has num_cryptos * 7 columns"  << I use num_crypto = 4 pairs but why 7 columns?

How do you prepare TradeEnv.data ? I do not see it being created anywhere in your code.

Thanks for further help in this matter.

EDIT:
* I see you set number of feature to 6: https://github.com/NickKaparinos/Automated-Cryptocurrency-trading-using-Deep-RL/blob/07dd37e790c5f42ec8c0034772773acbcd1d9452/trading_utilities.py#L27
* is 7 columns because you do: 4 feature (open, high, low, close) + month, day, hour ?

**Comment by NickKaparinos** [comment]
Yes. 7 = (open, high, low, close) + month, day, hour

The number of features is 6 because, the neural net does not see the open column (6 = 7 - open).

https://github.com/NickKaparinos/Automated-Cryptocurrency-trading-using-Deep-RL/blob/07dd37e790c5f42ec8c0034772773acbcd1d9452/trading_utilities.py#L126

I will add a screenshot of how my TradeEnv.data dataframe looks:
![image](https://user-images.githubusercontent.com/36237128/182539813-966697ac-0883-474a-981a-dc09dc332926.png)

If the problem persists, I suggest looking into TradeEnv._get_obs and TradeEnv.reset and comparing the dimension of the observation with the expected observation one.

**Comment by 0xdarkman** [comment]
Do your timeseries start at same moment in time?
It makes sense to me so they start at same date.
I was using data where my timeseries were NOT starting at same date.
I changed it and not I do not experience the problem.
